import { Metadata } from 'next';
import React from 'react'
import AboutUs from './AboutUs';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function page() {
  return (
    <div>
      <AboutUs/>
    </div>
  )
}
